### ISSUE TITLE
Feature Suggestion: Add more Convert Case options: To Lower Case, To Upper Case

### ISSUE THREAD

**Issue by andre-f-paggi** [madskristensen/Editorsk#2]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: 1.0.27

### Description
I would like to use this awesome extension to not only convert the selected text to Title Case, but to Lower and Upper Case too.

I can try making a PR if you agree.

Thanks for your awesome extensions. <3

**Comment by madskristensen** [comment]
Visual Studio already has those built in under **Edit -> Advanced -> To Upper Case**

**Comment by andre-f-paggi** [comment]
Oops, sorry for that. I installed VS in my local language and it got me confused. So sorry.
